 
<div>        
         <td>{{ profile.sport }}</td>
         <td>{{ profile.childsName }}</td>
         <td>{{ profile.dateOfBirth }}</td>
         <td>{{ profile.ageOnJuly31 }}</td>
         <td>{{ profile.playerStreetAddress }}</td>
         <td>{{ profile.playerCity }}</td>
         <td>{{ profile.zipCode }}</td>
         <td>{{ profile.gender }}</td>
         <td>{{ profile.primaryPhone }}</td>
         <td>{{ profile.cellPhone }}</td>
         <td>{{ profile.emergencyPhone }}</td>
         <td>{{ profile.parentsEmail }}</td>
         <td>{{ profile.experience }}</td>
         <td>{{ profile.yearsOfExperience }}</td>
         <td>{{ profile.schoolAttending }}</td>
         <td>{{ profile.gradeForFall }}</td>
         <td>{{ profile.lastTeamPlayedFor }}</td>
         <td>{{ profile.livesWith }}</td>
         <td>{{ profile.mothersName }}</td>
         <td>{{ profile.mothersAddress }}</td>
         <td>{{ profile.mothersCity }}</td>
         <td>{{ profile.mothersState }}</td>
         <td>{{ profile.mothersZipCode }}</td>
         <td>{{ profile.mothersPhone }}</td>
         <td>{{ profile.fathersName }}</td>
         <td>{{ profile.fathersAddress }}</td>
         <td>{{ profile.fathersCity }}</td>
         <td>{{ profile.fathersState }}</td>
         <td>{{ profile.fathersZipCode }}</td>
         <td>{{ profile.fathersPhone }}</td>
         <td>{{ profile.guardiansName }}</td>
         <td>{{ profile.guardiansAddress }}</td>
         <td>{{ profile.guardiansCity }}</td>
         <td>{{ profile.guardiansState }}</td>
         <td>{{ profile.guardiansZipCode }}</td>
         <td>{{ profile.guardiansPhone }}</td>
         <td>{{ profile.medicalAllergies }}</td>
         <td>{{ profile.medicationCurrentlyTaken }}</td>
         <td>{{ profile.agree }}</td>
</<td>{{ profile.div }}</td>>

$scope.myData.update({
      <td>{{ profile.sport }}</td>
      <td>{{ profile.childsName }}</td>
      <td>{{ profile.dateOfBirth }}</td>
      <td>{{ profile.ageOnJuly31 }}</td>
      <td>{{ profile.playerStreetAddress }}</td>
      <td>{{ profile.playerCity }}</td>
      <td>{{ profile.zipCode }}</td>
      <td>{{ profile.gender }}</td>
      <td>{{ profile.primaryPhone }}</td>
      <td>{{ profile.cellPhone }}</td>
      <td>{{ profile.emergencyPhone }}</td>
      <td>{{ profile.parentsEmail }}</td>
      <td>{{ profile.experience }}</td>
      <td>{{ profile.yearsOfExperience }}</td>
      <td>{{ profile.schoolAttending }}</td>
      <td>{{ profile.gradeForFall }}</td>
      <td>{{ profile.lastTeamPlayedFor }}</td>
      <td>{{ profile.livesWith }}</td>
      <td>{{ profile.mothersName }}</td>
      <td>{{ profile.mothersAddress }}</td>
      <td>{{ profile.mothersCity }}</td>
      <td>{{ profile.mothersState }}</td>
      <td>{{ profile.mothersZipCode }}</td>
      <td>{{ profile.mothersPhone }}</td>
      <td>{{ profile.fathersName }}</td>
      <td>{{ profile.fathersAddress }}</td>
      <td>{{ profile.fathersCity }}</td>
      <td>{{ profile.fathersState }}</td>
      <td>{{ profile.fathersZipCode }}</td>
      <td>{{ profile.fathersPhone }}</td>
      <td>{{ profile.guardiansName }}</td>
      <td>{{ profile.guardiansAddress }}</td>
      <td>{{ profile.guardiansCity }}</td>
      <td>{{ profile.guardiansState }}</td>
      <td>{{ profile.guardiansZipCode }}</td>
      <td>{{ profile.guardiansPhone }}</td>
      <td>{{ profile.medicalAllergies }}</td>
      <td>{{ profile.medicationCurrentlyTaken }}</td>
      <td>{{ profile.agree }}</td>
